apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-ext
  namespace: prometheus
  labels:
    app: prometheus-server-ext
spec:
  type: NodePort
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus-server-ext
