apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-1
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0b223d280ac31471f
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-2
spec:
  storageClassName: gp2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-04cef2258984a8548
    fsType: ext4
